webpack-contrib/webpack-defaults

package.json
Update includes the addition of Jest to the node Globals. 
Closes #12
=> chore(package): update to eslint-config-webpack v1.1.0

.travis.yml, package.json, src/tasks/package.js
- Adds standard travis build file
- updates travis:lint to execute nsp check
=> ci(Travis): defaults travis build

config.json, package.json, src/tasks/babel.js, src/tasks/package.js, src/tasks/travis.js
=> refactor: move min Node version to the config

.travis.yml, README.md, src/tasks/travis.js, templates/README.template, yarn.lock
- Service is simply too flaky to deploy across the organization and have it be of value
=> refactor(bithound): removes all bithound references

package.json, src/tasks/package.js
=> feat: add test:watch script

.travis.yml, src/tasks/travis.js
=> fix: overwrite .travis.yml

config.json, package.json, src/tasks/babel.js, src/tasks/travis.js
Also convert Node version to a string for consistency
=> webpack version config variable

.babelrc
=> fix(.babelrc): enable modules

src/tasks/babel.js, src/tasks/package.js
=> fix(src/tasks): enable modules, disable sourcemaps in build script 

package.json, src/tasks/package.js
- 'clean:dist':  =>  'clean'
- 'build:watch': use babel watch 
- 'start'
- 'serve:dev'
- nodemon
=> refactor(src/tasks/package.js): simplify scripts

.github/ISSUE_TEMPLATE.md, templates/.github/ISSUE_TEMPLATE.md
=> Comment issue template

config.json, src/tasks/templates.js, src/tasks/travis.js, templates/.travis.yml
- Runs canary stage as an allowed failure
- Moves travis.yml to a template until the anchor / alias issue can be resolved
- Comment related to the above added to travis.js
Closes #67
=> feat: Implement Travis stages

config.json
=> build(config): bump `minNode` v4.3.0...4.8.0

.github/CODEOWNERS, src/tasks/templates.js, templates/.github/CODEOWNERS
- Adds codeowners template https://help.github.com/articles/about-codeowners/
Closes #85
=> feat: Adds codeowners template

.eslintignore, README.md, config.json, package-lock.json, package.json, src/tasks/package.js, src/tasks/templates.js, templates/src/cjs.js, templates/src/index.js, templates/test/errors.test.js, templates/test/fixtures/fixture.js, templates/test/helpers/compiler.js, templates/test/options.test.js
- Reworks generation of `package.json` for consistent ordering using `json.set()`
- Grabs existing values if they exist & applies them to the new `package.json`
- Cleans up initial `src` & `test` templates
- Adds maint & active webpack versions to config
=>  refactor: Consistent package template generation

templates/.github/ISSUE_TEMPLATE.md, templates/.github/PULL_REQUEST_TEMPLATE.md
Issue and Pull Request templates are in need of deep, sweet love.
These templates can be updated/improved incrementally, but have been reviewed externally and are extremely effective in accurate and helpful issue and PR generation, and have generally been found to be easy to understand and follow.
=> chore: needed love for issue and PR templates

templates/.circleci/config.yml
There was an accidentally duplicated line.
=> chore: remove duplicate line

src/tasks/package.js
=> refactor(tasks/package): migrate from `@webpack-contrib/schema-utils` to `schema-utils`

templates/README.md
Avoid https://webpack.js.org/plugins/terser-webpack-plugin/ (look on bottom)
=> docs(templates/README): fix header links

.github/PULL_REQUEST_TEMPLATE.md
As in `webpack`, when creating people, they will see that tests are required, they will also give more information about their PR
=> feat: new pull request template

package-lock.json, package.json
=> refactor: use `npm-audit`

src/tasks/git.js
Ignore `*.iml` files what generate IntelliJ IDEA
No
No
=> fix(tasks/git): ignore IntelliJ IDEA files (`*.iml`)

package.json
=> fix(package): typo in `security` command (`scripts`)

templates/appveyor.yml
=> ci: update appveyor template

src/tasks/package.js
=> refactor: package.json generation

config.json, package.json, src/tasks/package.js
=> fix: relax minimum required nodejs

src/tasks/package.js
=> fix: relax minimum required webpack version

templates/.circleci/config.yml, templates/appveyor.yml
`webpack@5` require minimum `nodejs@8`
No
No
=> fix: increase nodejs version for canary builds

templates/appveyor.yml
run `npm run ci:test` instead `npm run ci:next`
No
No
=> fix: appveyor job name fro canary tests

templates/.circleci/config.yml, templates/appveyor.yml
Red CI status for some developers looks as if they made a mistake in tests/style code/lint rules/etc and it is not good.
No
No
=> fix: allow failures for canary builds

src/tasks/package.js
Latest jest doesn't require `babel-core` workaround
Yes - for existing default
No- for new project
No
=> chore: remove `babel-core`

templates/test/cjs.test.js
=> feat: add cjs test

src/tasks/package.js
=> chore: better order scripts

src/tasks/package.js, templates/.eslintrc.js, templates/.prettierrc
=> refactor: prettier configuration

src/tasks/package.js
=> fix: ci test script

config.json, src/tasks/eslint.js
No need, we already use `src` and `test` pattern in lint command
No
No
=> refactor: remove eslint ignore

src/tasks/package.js
Lint commit message before do commit
No
No
=> fix: commit linting

.circleci/config.yml, .eslintrc.js, .gitattributes, .github/ISSUE_TEMPLATE/BUG.md, .github/ISSUE_TEMPLATE/FEATURE.md, .github/ISSUE_TEMPLATE/MODIFICATION.md, .prettierrc, README.md, appveyor.yml, package-lock.json, package.json
=> chore(defaults): update

templates/.github/ISSUE_TEMPLATE/BUG.md
The slang is not obvious what it refers to for non-native speakers.
=> Remove slang from bug issue template

package-lock.json, templates/test/__snapshots__/loader.test.js.snap, templates/test/__snapshots__/options.test.js.snap, templates/test/__snapshots__/validation.test.js.snap, templates/test/validation.test.js
Simple PR which audit and fix npm dependencies. 
/CC @evilebottnawi
=> npm audit fix dependencies

README.md, src/tasks/templates.js
Navigating the docs should work; reading the comments should make sense.
=> docs(typo): fixing multiple typo issues

.prettierignore, lint-staged.config.js, src/tasks/issue_template.js, templates/.github/ISSUE_TEMPLATE/FEATURE.md, templates/.github/ISSUE_TEMPLATE/MODIFICATION.md
=> fix: replacing package name in templates

templates/lint-staged.config.js
fix configuration for `lint-staged`
No
No
=> fix: lint-staged configuration
