lib/post_install.js
package.json

This generates a build if it's missing. Now you can consume defaults outside of npm through revisions/tags.

feat - Add a post install script

---

.babelrc
package.json
src/tasks/babel.js
src/tasks/package.js
yarn.lock

- Updates webpack-defaults to both use and output `babel-preset-env`
The working webpack-defaults `.babelrc` is the actual output from the `sync` command.
I've tested this configuration by modifying @bebraw's branch in file-loader, the transpiled output checks out and the Jest suite functions as expected.
> The modified file-loader has been tested on every supported major NodeJS version in `engines`
I'm satisfied with the concept and it's output. There is a slight performance hit on the preprecessing for the Jest runs but it's ~ 0.3 seconds and minimal enough to not block the feature imo.
Closed #6

feat(babel): convert to babel-preset-env

---

src/tasks/package.js
templates/src/cjs.js

Adds a CommonJS proxy to handle the `export default` issue while retaining the ability to use ES Modules internally.
Closes #23

feat: add commonjs proxy for es modules

---

.babelrc
package.json
src/tasks/babel.js
src/tasks/package.js
yarn.lock

- This was a transform that existed in `babel-preset-webpack` that didn't migrate over to the preset-env setup
Resolves #37

fix(babel): Adds object-rest-spread to env

---

src/tasks/templates.js

The template was added but I forgot to add it to `templates.js` so it's actually written out.
Closes #44

fix: add missing cjs.js to filesOnce

---

.babelrc
package.json
src/tasks/babel.js
yarn.lock

Fixes a warning coming from the `.babelrc` below.
Caused by the `node` target value currently being of type decimal.
```
"presets": [
[
"env",
{
"useBuiltIns": true,
"targets": {
"node": 4.3
},
"exclude": [
"transform-async-to-generator",
"transform-regenerator"
]
}
]
],
```

fix(babelrc): Preset node target should be a string

---

package.json
yarn.lock

Updates to latest major version of Jest which has a bunch of useful fixes & features.
Most of the breaking changes shouldn't have an impact on our test suites with the possible & notable exception of the new css loader which is leveraging snapshots ( need to test this to be sure ).
See https://github.com/facebook/jest/blob/master/CHANGELOG.md#jest-2000 for more information on the release.

chore(package): Update to Jest 20

---

config.json

Increases the defined webpack version used for testing in the `.travis.yml` to the currently released minor version of `2.6.0`

chore(travis): Bump webpack test version

---

src/tasks/appveyor.js
src/tasks/package.js

Adds an appveyor build file to `webpack-defaults`
- The service has been configured for the org - https://ci.appveyor.com/projects
- The service account has already been configured - https://github.com/webpack-contrib-appveyor
- Teams within contrib have been assigned the proper permissions to access the service.
Output ...
```
branches:
only:
- master
init:
- git config --global core.autocrlf input
environment:
matrix:
- nodejs_version: 7
webpack_version: 2.2.0
job_part: test
- nodejs_version: 6
webpack_version: 2.2.0
job_part: test
- nodejs_version: 4.3
webpack_version: 2.2.0
job_part: test
install:
- ps: Install-Product node $env:nodejs_version x64
- npm install
build: off
matrix:
fast_finish: true
before_test:
- cmd: npm install webpack@^%webpack_version%
test_script:
- node --version …
```

feat: Adds appveyor build file

---

src/tasks/package.js

`release` should just execute the standard-version bin. It's currently trying to execute an npm script with the same name.

fix: Release script should not exec `npm run`

---

src/tasks/package.js

- These may end up being customized over time per project but they should be there with this as the current default.
Adds a peerDependency for Webpack effectively dropping support for 1.x with the application of webpack-defaults.
Closes #63

feat: Enforce peerDependencies via defaults

---

config.json

Wasn't added with the template.

fix: Adds missing appveyor task in config

---

templates/.travis.yml

Template is currently using `nodejs` as a key for the new stages config which is deprecated.

fix: Include was using the deprecated nodejs key

---

src/tasks/package.js

As per the comment from https://github.com/webpack-contrib/less-loader/pull/208#discussion_r123869314

refactor: remove `webpack v3.0.0-rc` from `peerDependencies`

---

config.json
src/tasks/appveyor.js

As per the comment in https://github.com/webpack-contrib/less-loader/pull/208#discussion_r123869286

refactor(appveyor): install exact webpack version

---

src/tasks/package.js

Continuing the discussion from https://github.com/webpack-contrib/less-loader/pull/208#discussion_r123879351
I believe webpack should be included as a dev dependency because:
* checking out a webpack-contrib repo, running `npm install` and `npm t` should just work. Instead you're greeted with this error message, it's not immediately obvious that webpack needs to be installed with `npm install webpack`. Some users will just give up here and not bother contributing to the repo.
* secondly once running `npm install webpack` to get the tests running, because of the npm 5 requirement, `package.json` and `package-lock.json` are automatically updated and will appear in the git diff before the user has even made any changes. Based on my own experience with open source, people will commit these …

feat: add `webpack` as a `devDependency`

---

src/tasks/appveyor.js

Node 4.3 uses npm2 which doesn't hoist dependencies, so then you get cryptic error messages on appveyor about regeneratorRuntime not being defined when using async functions in tests. Travis already forces npm5 so we may as well enforce it here as well.

fix(appveyor): always use latest npm

---

.travis.yml
templates/.travis.yml

Based on https://github.com/webpack-contrib/file-loader/pull/183#issuecomment-328289654.
Issue around `npm` - https://github.com/npm/npm/issues/18395.
From `slack`:
```shell
sokra [12:29 PM] 
we are no longer chained to 4.3. You can use that lastest 4.x (node.js version currently in maintenance mode.
4.3 was because of AWS, but they upgraded to node 6.x so this is no longer an issue.
```

feat: update minimum required `node.js` version to `4.8` for travis CI

---

src/tasks/readme.js
templates/README.template

refactor(templates/README): standardize

---

package.json
src/tasks/package.js

This PR updates both the `package.json` in the repo for the module _and_ the package template copied to repos that use `webpack-defaults`. The update is a highly semantic and uses an ordering that is meant to draw attention to the most important bits of a package's metadata first.

refactor: restructure package.json+template semantically

---

templates/commitlint.config.js

fix(commitlint): fix type-enum options

---

config.json
src/tasks/issue_template.js
src/tasks/package.js
src/tasks/templates.js
templates/.github/ISSUE_TEMPLATE.md

Fixes missed `keywords` in package.json.
Replaces package name in `ISSUE_TEMPLATE` (It's current static as `webpack-serve`, which isn't right)

fix: add keywords to package, replace name in issue template

---

src/tasks/package.js

On the surface it may not seem like copying a `bin` property would be useful. But defaults comes packed with a lot of added bonus in linting, process, etc. that non-loaders, non-plugins can and should benefit from.

fix(package): copy existing bin property

---

README.md
templates/README.md

This adds a badge to the readme with the install size.
Related: https://github.com/webpack-contrib/webpack-command/pull/9

Add badge for npm install size

---

templates/README.md

@shellscape There was a typo from #113 (oops)

Fix hyperlink to size badge

---

templates/.circleci/config.yml

This adds the Node.js 10 image to the default configurations.
Reference: https://github.com/webpack-contrib/mini-css-extract-plugin/pull/136#issuecomment-388033026

chore: add Node.js 10 image

---

package-lock.json
package.json

This updates `lint-staged` to the latest. 
`lint-staged` has breaking changes between v6 and v7, these should not affect this
- requires node >6, as does this
- can no longer run custom npm scripts without using `npm run` (this does not run any custom npm script)
Reasoning behind this is that `lint-staged` does not recognise node v10 until v7.0.5, so anyone contributing using node v10 will be faced with this when committing -

refactor: upgrade lint-staged dependency

---

.github/CONTRIBUTING.md
README.md
package.json
src/tasks/package.js

This PR changes the following:
1. Syncs the README with the template README we apply to other contrib repos. Fixes some broken images, links along the way. (Note: we removed the contributor avatars in the template readme some time ago)
2. Adds CONTRIBUTING.md to the root .github directory (it should be there), which matches the template.
3. Changes the package to a scoped NPM name. See below.
It was decided some time ago that packages which only have relevant use within webpack-contrib/webpack and not outside of the org or the orgs packages, should be scoped. The first package to adopt this new mantra was config-loader. Packages which aren't intended for public consumption but are utility, or auxiliary packages also apply. That makes webpack-defaults qualify.

chore: scope the package, sync readme with template

---

templates/.circleci/config.yml
templates/appveyor.yml

ci: add `node >= v10.0.0` and skip canary testing on outdated versions

---

templates/appveyor.yml

fix: install `tag-versions` for `canary` tests

---

src/tasks/package.js
templates/.circleci/config.yml

- use `npm audit` (it is require latest `npm`)
- remove `publish`
- use `npm@latest` where it is possible
- use `npm ci` where it is possible (it is very fast)
- fix some typos
- Fixes #123

ci: refactor setup

---

src/tasks/package.js

chore: remove unnecessary release npm scripts

---

src/tasks/package.js

By default we should install `@webpack-contrib/defaults` otherwise `npm run defaults` doesn't work.
No
No

fix(tasks/package): switch from `webpack-defaults` to `@webpack-contrib/defaults`

---

templates/README.md

We don't need this, `npm` already do error/warning if you `node` or `webpack` version is not compatibility. Also it is require rewrite this after updates.

docs(README): remove `Requirements` section

---

src/tasks/package.js

PR to replace the deprecated `prepublish` with `prepare`.
/CC @evilebottnawi

Replace prepublish npm script with prepare

---

package.json

Adds funding field to `package.json` to show fund this package button in npmjs.org. All other plugins and loaders have this

chore: add funding field to package.json
